# Generated by Django 2.2.12 on 2022-07-22 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20220718_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userId', to=settings.AUTH_USER_MODEL),
        ),
    ]
