# Generated by Django 2.2.12 on 2022-07-22 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='categoryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.Categories'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('discription', models.CharField(max_length=64)),
                ('bid', models.FloatField(max_length=50)),
                ('urlImage', models.ImageField(max_length=700, upload_to='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('categoryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.Categories')),
                ('listId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.Listing')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
