# Generated by Django 2.2.12 on 2022-07-26 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='end',
            name='categoryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.Categories'),
        ),
    ]
