# Generated by Django 2.2.12 on 2022-07-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_end_categoryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='end',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
