# Generated by Django 2.2.12 on 2022-07-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_end_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='end',
            name='discription',
            field=models.CharField(default='', max_length=64),
        ),
    ]
