# Generated by Django 2.2.12 on 2022-07-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_end_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='close',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='End',
        ),
    ]
